// Code generated by mockery v2.14.1. DO NOT EDIT.

package user

import (
	entity "posterr/database/entity"

	mock "github.com/stretchr/testify/mock"
)

// UserServiceInteface is an autogenerated mock type for the UserServiceInteface type
type UserServiceInteface struct {
	mock.Mock
}

// Find provides a mock function with given fields: userUuid
func (_m *UserServiceInteface) Find(userUuid string) (entity.User, error) {
	ret := _m.Called(userUuid)

	var r0 entity.User
	if rf, ok := ret.Get(0).(func(string) entity.User); ok {
		r0 = rf(userUuid)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userUuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserServiceInteface interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserServiceInteface creates a new instance of UserServiceInteface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserServiceInteface(t mockConstructorTestingTNewUserServiceInteface) *UserServiceInteface {
	mock := &UserServiceInteface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
