version: "2"
services:
  app:
    image: golang
    restart: always
    working_dir: /var/app
    volumes:
      - .:/var/app
    ports:
      - 8001:8000
    depends_on:
      - database
    networks:
      - default
    environment:
      - "POSTGRES_PASSWORD=123456"
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgres:

networks:
  default: